<a href="https://colab.research.google.com/github/seeedata/Dacon/blob/main/%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EC%B1%84%EB%84%90%20%EC%A0%9C%ED%92%88%20%ED%8C%90%EB%A7%A4%EB%9F%89%20%EC%98%88%EC%B8%A1%20AI%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%ED%95%B4%EC%BB%A4%ED%86%A4/0818%20%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%85%8B%20%EB%B3%80%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#import

In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 16 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-nanum all 20200506-1 [10.3 MB]
Fetched 10.3 MB in 0s (23.3 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 120831 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['font.family'] = 'NanumBarunGothic'

import warnings
warnings.filterwarnings('ignore')

from datetime import datetime

#train 데이터셋 변형

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/LGaimers/data/train.csv', encoding='cp949')
train

,ID,제품,대분류,중분류,소분류,브랜드,2022-01-01,2022-01-02,2022-01-03,2022-01-04,...,2023-03-26,2023-03-27,2023-03-28,2023-03-29,2023-03-30,2023-03-31,2023-04-01,2023-04-02,2023-04-03,2023-04-04
0,0,B002-00001-00001,B002-C001-0002,B002-C002-0007,B002-C003-0038,B002-00001,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,B002-00002-00001,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,0,0,0,0,...,0,0,0,1,3,2,0,0,2,0
2,2,B002-00002-00002,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,B002-00002-00003,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,B002-00003-00001,B002-C001-0001,B002-C002-0001,B002-C003-0003,B002-00003,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15885,15885,B002-03799-00002,B002-C001-0003,B002-C002-0008,B002-C003-0042,B002-03799,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15886,15886,B002-03799-00003,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-03799,0,0,0,0,...,0,0,0,3,0,2,4,1,1,3
15887,15887,B002-03799-00004,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-03799,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15888,15888,B002-03799-00005,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-03799,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
15889,15889,B002-03799-00010,B002-C001-0002,B002-C002-0004,B002-C003-0020,B002-03799,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15890 entries, 0 to 15889
Columns: 465 entries, ID to 2023-04-04
dtypes: int64(460), object(5)
memory usage: 56.4+ MB

In [ ]:
train.isna().sum()

ID            0
제품            0
대분류           0
중분류           0
소분류           0
             ..
2023-03-31    0
2023-04-01    0
2023-04-02    0
2023-04-03    0
2023-04-04    0
Length: 465, dtype: int64

In [ ]:
df1 = train.drop(columns = ['제품', '대분류', '중분류', '소분류', '브랜드']); df1

,ID,2022-01-01,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,...,2023-03-26,2023-03-27,2023-03-28,2023-03-29,2023-03-30,2023-03-31,2023-04-01,2023-04-02,2023-04-03,2023-04-04
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,3,2,0,0,2,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15885,15885,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15886,15886,0,0,0,0,0,0,0,0,0,...,0,0,0,3,0,2,4,1,1,3
15887,15887,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15888,15888,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
15889,15889,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df1 = df1.melt('ID'); df1

            ID    variable  value
0            0  2022-01-01      0
1            1  2022-01-01      0
2            2  2022-01-01      0
3            3  2022-01-01      0
4            4  2022-01-01      0
...        ...         ...    ...
7293505  15885  2023-04-04      0
7293506  15886  2023-04-04      3
7293507  15887  2023-04-04      0
7293508  15888  2023-04-04      2
7293509  15889  2023-04-04      0

[7293510 rows x 3 columns]

In [ ]:
df1.sort_values(['ID', 'variable'], ascending=True, inplace=True); df1

            ID    variable  value
0            0  2022-01-01      0
15890        0  2022-01-02      0
31780        0  2022-01-03      0
47670        0  2022-01-04      0
63560        0  2022-01-05      0
...        ...         ...    ...
7229949  15889  2023-03-31      0
7245839  15889  2023-04-01      0
7261729  15889  2023-04-02      0
7277619  15889  2023-04-03      0
7293509  15889  2023-04-04      0

[7293510 rows x 3 columns]

In [ ]:
df1.set_index('variable', inplace=True); df1

               ID  value
variable
2022-01-01      0      0
2022-01-02      0      0
2022-01-03      0      0
2022-01-04      0      0
2022-01-05      0      0
...           ...    ...
2023-03-31  15889      0
2023-04-01  15889      0
2023-04-02  15889      0
2023-04-03  15889      0
2023-04-04  15889      0

[7293510 rows x 2 columns]

In [ ]:
df1 = df1.rename(columns = {'value': 'count'}); df1

               ID  count
variable
2022-01-01      0      0
2022-01-02      0      0
2022-01-03      0      0
2022-01-04      0      0
2022-01-05      0      0
...           ...    ...
2023-03-31  15889      0
2023-04-01  15889      0
2023-04-02  15889      0
2023-04-03  15889      0
2023-04-04  15889      0

[7293510 rows x 2 columns]

In [ ]:
df1.to_csv('/content/drive/MyDrive/Colab Notebooks/LGaimers/8.18_onlytrain.csv')

#sales 데이터셋 변형

In [ ]:
sales = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/LGaimers/data/sales.csv', encoding='cp949'); sales

,ID,제품,대분류,중분류,소분류,브랜드,2022-01-01,2022-01-02,2022-01-03,2022-01-04,...,2023-03-26,2023-03-27,2023-03-28,2023-03-29,2023-03-30,2023-03-31,2023-04-01,2023-04-02,2023-04-03,2023-04-04
0,0,B002-00001-00001,B002-C001-0002,B002-C002-0007,B002-C003-0038,B002-00001,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,B002-00002-00001,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,0,0,0,0,...,0,0,0,22400,67200,44800,0,0,44800,0
2,2,B002-00002-00002,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,B002-00002-00003,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,B002-00003-00001,B002-C001-0001,B002-C002-0001,B002-C003-0003,B002-00003,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15885,15885,B002-03799-00002,B002-C001-0003,B002-C002-0008,B002-C003-0042,B002-03799,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15886,15886,B002-03799-00003,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-03799,0,0,0,0,...,0,0,0,60690,0,40460,80920,20230,20230,60690
15887,15887,B002-03799-00004,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-03799,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15888,15888,B002-03799-00005,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-03799,0,0,0,0,...,0,0,0,0,0,0,0,0,0,27300
15889,15889,B002-03799-00010,B002-C001-0002,B002-C002-0004,B002-C003-0020,B002-03799,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df2 = sales.drop(columns = ['제품', '대분류', '중분류', '소분류', '브랜드'])
df2 = df2.melt('ID')
df2.sort_values(['ID', 'variable'], ascending=True, inplace=True)
df2.set_index('variable', inplace=True); df2

               ID  value
variable
2022-01-01      0      0
2022-01-02      0      0
2022-01-03      0      0
2022-01-04      0      0
2022-01-05      0      0
...           ...    ...
2023-03-31  15889      0
2023-04-01  15889      0
2023-04-02  15889      0
2023-04-03  15889      0
2023-04-04  15889      0

[7293510 rows x 2 columns]

In [ ]:
df2 = df2.rename(columns = {'value': 'sales'}); df2

               ID  sales
variable
2022-01-01      0      0
2022-01-02      0      0
2022-01-03      0      0
2022-01-04      0      0
2022-01-05      0      0
...           ...    ...
2023-03-31  15889      0
2023-04-01  15889      0
2023-04-02  15889      0
2023-04-03  15889      0
2023-04-04  15889      0

[7293510 rows x 2 columns]

In [ ]:
df2.to_csv('/content/drive/MyDrive/Colab Notebooks/LGaimers/8.18_onlysales.csv')

#train과 sales 데이터 병합

In [ ]:
df = pd.merge(df1, df2, on='ID')
#df.to_csv('/content/drive/MyDrive/Colab Notebooks/LGaimers/train+sales.csv')